/**
 * capitals.js
 * Capital city data and aliases.
 *
 *   CAPITALS        – ISO_A3 → { en, fr, lat, lng }
 *   CAPITAL_ALIASES – normalized string → ISO_A3  (alternate spellings)
 */

/**
 * Each entry: English name, French name, latitude, longitude.
 * French name is identical to English when there is no common French variant.
 * @type {Record<string, {en:string, fr:string, lat:number, lng:number}>}
 */
export const CAPITALS = {
  AFG: { en:'Kabul',           fr:'Kaboul',              lat: 34.53,  lng:  69.17 },
  ALB: { en:'Tirana',          fr:'Tirana',              lat: 41.33,  lng:  19.82 },
  DZA: { en:'Algiers',         fr:'Alger',               lat: 36.75,  lng:   3.04 },
  AND: { en:'Andorra la Vella',fr:'Andorre-la-Vieille',  lat: 42.51,  lng:   1.52 },
  AGO: { en:'Luanda',          fr:'Luanda',              lat: -8.84,  lng:  13.23 },
  ATG: { en:"Saint John's",    fr:"Saint John's",        lat: 17.12,  lng: -61.85 },
  ARG: { en:'Buenos Aires',    fr:'Buenos Aires',        lat:-34.60,  lng: -58.38 },
  ARM: { en:'Yerevan',         fr:'Erevan',              lat: 40.18,  lng:  44.51 },
  AUS: { en:'Canberra',        fr:'Canberra',            lat:-35.28,  lng: 149.13 },
  AUT: { en:'Vienna',          fr:'Vienne',              lat: 48.21,  lng:  16.37 },
  AZE: { en:'Baku',            fr:'Bakou',               lat: 40.41,  lng:  49.87 },
  BHS: { en:'Nassau',          fr:'Nassau',              lat: 25.06,  lng: -77.34 },
  BHR: { en:'Manama',          fr:'Manama',              lat: 26.23,  lng:  50.58 },
  BGD: { en:'Dhaka',           fr:'Dacca',               lat: 23.81,  lng:  90.41 },
  BRB: { en:'Bridgetown',      fr:'Bridgetown',          lat: 13.10,  lng: -59.61 },
  BLR: { en:'Minsk',           fr:'Minsk',               lat: 53.90,  lng:  27.57 },
  BEL: { en:'Brussels',        fr:'Bruxelles',           lat: 50.85,  lng:   4.35 },
  BLZ: { en:'Belmopan',        fr:'Belmopan',            lat: 17.25,  lng: -88.77 },
  BEN: { en:'Porto-Novo',      fr:'Porto-Novo',          lat:  6.50,  lng:   2.63 },
  BTN: { en:'Thimphu',         fr:'Thimphou',            lat: 27.47,  lng:  89.64 },
  BOL: { en:'La Paz',          fr:'La Paz',              lat:-16.50,  lng: -68.15 },
  BIH: { en:'Sarajevo',        fr:'Sarajevo',            lat: 43.86,  lng:  18.41 },
  BWA: { en:'Gaborone',        fr:'Gaborone',            lat:-24.65,  lng:  25.91 },
  BRA: { en:'Brasilia',        fr:'Brasilia',            lat:-15.79,  lng: -47.88 },
  BRN: { en:'Bandar Seri Begawan', fr:'Bandar Seri Begawan', lat:  4.94, lng: 114.95 },
  BGR: { en:'Sofia',           fr:'Sofia',               lat: 42.70,  lng:  23.32 },
  BFA: { en:'Ouagadougou',     fr:'Ouagadougou',         lat: 12.37,  lng:  -1.52 },
  BDI: { en:'Gitega',          fr:'Gitega',              lat: -3.43,  lng:  29.93 },
  CPV: { en:'Praia',           fr:'Praia',               lat: 14.93,  lng: -23.51 },
  KHM: { en:'Phnom Penh',      fr:'Phnom Penh',          lat: 11.56,  lng: 104.92 },
  CMR: { en:'Yaoundé',         fr:'Yaoundé',             lat:  3.87,  lng:  11.52 },
  CAN: { en:'Ottawa',          fr:'Ottawa',              lat: 45.42,  lng: -75.70 },
  CAF: { en:'Bangui',          fr:'Bangui',              lat:  4.36,  lng:  18.56 },
  TCD: { en:"N'Djamena",       fr:"N'Djaména",           lat: 12.13,  lng:  15.05 },
  CHL: { en:'Santiago',        fr:'Santiago',            lat:-33.45,  lng: -70.67 },
  CHN: { en:'Beijing',         fr:'Pékin',               lat: 39.90,  lng: 116.40 },
  COL: { en:'Bogotá',          fr:'Bogota',              lat:  4.71,  lng: -74.07 },
  COM: { en:'Moroni',          fr:'Moroni',              lat:-11.70,  lng:  43.26 },
  COG: { en:'Brazzaville',     fr:'Brazzaville',         lat: -4.27,  lng:  15.28 },
  COD: { en:'Kinshasa',        fr:'Kinshasa',            lat: -4.44,  lng:  15.27 },
  CRI: { en:'San José',        fr:'San José',            lat:  9.93,  lng: -84.08 },
  CIV: { en:'Yamoussoukro',    fr:'Yamoussoukro',        lat:  6.82,  lng:  -5.28 },
  HRV: { en:'Zagreb',          fr:'Zagreb',              lat: 45.81,  lng:  15.98 },
  CUB: { en:'Havana',          fr:'La Havane',           lat: 23.11,  lng: -82.37 },
  CYP: { en:'Nicosia',         fr:'Nicosie',             lat: 35.17,  lng:  33.37 },
  CZE: { en:'Prague',          fr:'Prague',              lat: 50.08,  lng:  14.42 },
  DNK: { en:'Copenhagen',      fr:'Copenhague',          lat: 55.68,  lng:  12.57 },
  DJI: { en:'Djibouti',        fr:'Djibouti',            lat: 11.59,  lng:  43.15 },
  DMA: { en:'Roseau',          fr:'Roseau',              lat: 15.30,  lng: -61.39 },
  DOM: { en:'Santo Domingo',   fr:'Saint-Domingue',      lat: 18.49,  lng: -69.90 },
  ECU: { en:'Quito',           fr:'Quito',               lat: -0.18,  lng: -78.47 },
  EGY: { en:'Cairo',           fr:'Le Caire',            lat: 30.04,  lng:  31.24 },
  SLV: { en:'San Salvador',    fr:'San Salvador',        lat: 13.69,  lng: -89.19 },
  GNQ: { en:'Malabo',          fr:'Malabo',              lat:  3.75,  lng:   8.78 },
  ERI: { en:'Asmara',          fr:'Asmara',              lat: 15.34,  lng:  38.93 },
  EST: { en:'Tallinn',         fr:'Tallinn',             lat: 59.44,  lng:  24.75 },
  SWZ: { en:'Mbabane',         fr:'Mbabane',             lat:-26.32,  lng:  31.13 },
  ETH: { en:'Addis Ababa',     fr:'Addis-Abeba',         lat:  9.02,  lng:  38.75 },
  FJI: { en:'Suva',            fr:'Suva',                lat:-18.14,  lng: 178.44 },
  FIN: { en:'Helsinki',        fr:'Helsinki',            lat: 60.17,  lng:  24.94 },
  FRA: { en:'Paris',           fr:'Paris',               lat: 48.86,  lng:   2.35 },
  GAB: { en:'Libreville',      fr:'Libreville',          lat:  0.39,  lng:   9.45 },
  GMB: { en:'Banjul',          fr:'Banjul',              lat: 13.45,  lng: -16.58 },
  GEO: { en:'Tbilisi',         fr:'Tbilissi',            lat: 41.72,  lng:  44.79 },
  DEU: { en:'Berlin',          fr:'Berlin',              lat: 52.52,  lng:  13.41 },
  GHA: { en:'Accra',           fr:'Accra',               lat:  5.56,  lng:  -0.19 },
  GRC: { en:'Athens',          fr:'Athènes',             lat: 37.98,  lng:  23.73 },
  GRD: { en:"Saint George's",  fr:"Saint-Georges",       lat: 12.05,  lng: -61.75 },
  GTM: { en:'Guatemala City',  fr:'Guatemala',           lat: 14.63,  lng: -90.51 },
  GIN: { en:'Conakry',         fr:'Conakry',             lat:  9.64,  lng: -13.58 },
  GNB: { en:'Bissau',          fr:'Bissau',              lat: 11.86,  lng: -15.60 },
  GUY: { en:'Georgetown',      fr:'Georgetown',          lat:  6.80,  lng: -58.16 },
  HTI: { en:'Port-au-Prince',  fr:'Port-au-Prince',      lat: 18.54,  lng: -72.34 },
  HND: { en:'Tegucigalpa',     fr:'Tegucigalpa',         lat: 14.07,  lng: -87.21 },
  HUN: { en:'Budapest',        fr:'Budapest',            lat: 47.50,  lng:  19.04 },
  ISL: { en:'Reykjavik',       fr:'Reykjavik',           lat: 64.14,  lng: -21.90 },
  IND: { en:'New Delhi',       fr:'New Delhi',           lat: 28.61,  lng:  77.21 },
  IDN: { en:'Jakarta',         fr:'Jakarta',             lat: -6.21,  lng: 106.85 },
  IRN: { en:'Tehran',          fr:'Téhéran',             lat: 35.69,  lng:  51.39 },
  IRQ: { en:'Baghdad',         fr:'Bagdad',              lat: 33.31,  lng:  44.37 },
  IRL: { en:'Dublin',          fr:'Dublin',              lat: 53.35,  lng:  -6.26 },
  ISR: { en:'Jerusalem',       fr:'Jérusalem',           lat: 31.77,  lng:  35.23 },
  ITA: { en:'Rome',            fr:'Rome',                lat: 41.90,  lng:  12.50 },
  JAM: { en:'Kingston',        fr:'Kingston',            lat: 18.00,  lng: -76.79 },
  JPN: { en:'Tokyo',           fr:'Tokyo',               lat: 35.68,  lng: 139.69 },
  JOR: { en:'Amman',           fr:'Amman',               lat: 31.95,  lng:  35.93 },
  KAZ: { en:'Astana',          fr:'Astana',              lat: 51.17,  lng:  71.43 },
  KEN: { en:'Nairobi',         fr:'Nairobi',             lat: -1.29,  lng:  36.82 },
  KIR: { en:'Tarawa',          fr:'Tarawa',              lat:  1.45,  lng: 173.00 },
  PRK: { en:'Pyongyang',       fr:'Pyongyang',           lat: 39.02,  lng: 125.75 },
  KOR: { en:'Seoul',           fr:'Séoul',               lat: 37.57,  lng: 126.98 },
  KWT: { en:'Kuwait City',     fr:'Koweït',              lat: 29.37,  lng:  47.98 },
  KGZ: { en:'Bishkek',         fr:'Bichkek',             lat: 42.87,  lng:  74.59 },
  LAO: { en:'Vientiane',       fr:'Vientiane',           lat: 17.97,  lng: 102.63 },
  LVA: { en:'Riga',            fr:'Riga',                lat: 56.95,  lng:  24.11 },
  LBN: { en:'Beirut',          fr:'Beyrouth',            lat: 33.89,  lng:  35.50 },
  LSO: { en:'Maseru',          fr:'Maseru',              lat:-29.31,  lng:  27.48 },
  LBR: { en:'Monrovia',        fr:'Monrovia',            lat:  6.30,  lng: -10.80 },
  LBY: { en:'Tripoli',         fr:'Tripoli',             lat: 32.89,  lng:  13.18 },
  LIE: { en:'Vaduz',           fr:'Vaduz',               lat: 47.14,  lng:   9.52 },
  LTU: { en:'Vilnius',         fr:'Vilnius',             lat: 54.69,  lng:  25.28 },
  LUX: { en:'Luxembourg',      fr:'Luxembourg',          lat: 49.61,  lng:   6.13 },
  MDG: { en:'Antananarivo',    fr:'Antananarivo',        lat:-18.91,  lng:  47.52 },
  MWI: { en:'Lilongwe',        fr:'Lilongwe',            lat:-13.97,  lng:  33.79 },
  MYS: { en:'Kuala Lumpur',    fr:'Kuala Lumpur',        lat:  3.14,  lng: 101.69 },
  MDV: { en:'Malé',            fr:'Malé',                lat:  4.18,  lng:  73.51 },
  MLI: { en:'Bamako',          fr:'Bamako',              lat: 12.65,  lng:  -8.00 },
  MLT: { en:'Valletta',        fr:'La Valette',          lat: 35.90,  lng:  14.51 },
  MHL: { en:'Majuro',          fr:'Majuro',              lat:  7.09,  lng: 171.38 },
  MRT: { en:'Nouakchott',      fr:'Nouakchott',          lat: 18.09,  lng: -15.98 },
  MUS: { en:'Port Louis',      fr:'Port-Louis',          lat:-20.16,  lng:  57.50 },
  MEX: { en:'Mexico City',     fr:'Mexico',              lat: 19.43,  lng: -99.13 },
  FSM: { en:'Palikir',         fr:'Palikir',             lat:  6.92,  lng: 158.15 },
  MDA: { en:'Chișinău',        fr:'Chișinău',            lat: 47.01,  lng:  28.86 },
  MCO: { en:'Monaco',          fr:'Monaco',              lat: 43.73,  lng:   7.42 },
  MNG: { en:'Ulaanbaatar',     fr:'Oulan-Bator',         lat: 47.91,  lng: 106.91 },
  MNE: { en:'Podgorica',       fr:'Podgorica',           lat: 42.44,  lng:  19.26 },
  MAR: { en:'Rabat',           fr:'Rabat',               lat: 34.02,  lng:  -6.84 },
  MOZ: { en:'Maputo',          fr:'Maputo',              lat:-25.97,  lng:  32.57 },
  MMR: { en:'Naypyidaw',       fr:'Naypyidaw',           lat: 19.76,  lng:  96.07 },
  NAM: { en:'Windhoek',        fr:'Windhoek',            lat:-22.57,  lng:  17.08 },
  NRU: { en:'Yaren',           fr:'Yaren',               lat: -0.55,  lng: 166.92 },
  NPL: { en:'Kathmandu',       fr:'Katmandou',           lat: 27.72,  lng:  85.32 },
  NLD: { en:'Amsterdam',       fr:'Amsterdam',           lat: 52.37,  lng:   4.90 },
  NZL: { en:'Wellington',      fr:'Wellington',           lat:-41.29,  lng: 174.78 },
  NIC: { en:'Managua',         fr:'Managua',             lat: 12.11,  lng: -86.27 },
  NER: { en:'Niamey',          fr:'Niamey',              lat: 13.51,  lng:   2.11 },
  NGA: { en:'Abuja',           fr:'Abuja',               lat:  9.06,  lng:   7.49 },
  MKD: { en:'Skopje',          fr:'Skopje',              lat: 42.00,  lng:  21.43 },
  NOR: { en:'Oslo',            fr:'Oslo',                lat: 59.91,  lng:  10.75 },
  OMN: { en:'Muscat',          fr:'Mascate',             lat: 23.59,  lng:  58.54 },
  PAK: { en:'Islamabad',       fr:'Islamabad',           lat: 33.69,  lng:  73.04 },
  PLW: { en:'Ngerulmud',       fr:'Ngerulmud',           lat:  7.50,  lng: 134.62 },
  PAN: { en:'Panama City',     fr:'Panama',              lat:  8.98,  lng: -79.52 },
  PNG: { en:'Port Moresby',    fr:'Port Moresby',        lat: -9.48,  lng: 147.15 },
  PRY: { en:'Asunción',        fr:'Asuncion',            lat:-25.26,  lng: -57.58 },
  PER: { en:'Lima',            fr:'Lima',                lat:-12.05,  lng: -77.04 },
  PHL: { en:'Manila',          fr:'Manille',             lat: 14.60,  lng: 120.98 },
  POL: { en:'Warsaw',          fr:'Varsovie',            lat: 52.23,  lng:  21.01 },
  PRT: { en:'Lisbon',          fr:'Lisbonne',            lat: 38.72,  lng:  -9.14 },
  QAT: { en:'Doha',            fr:'Doha',                lat: 25.29,  lng:  51.53 },
  ROU: { en:'Bucharest',       fr:'Bucarest',            lat: 44.43,  lng:  26.10 },
  RUS: { en:'Moscow',          fr:'Moscou',              lat: 55.76,  lng:  37.62 },
  RWA: { en:'Kigali',          fr:'Kigali',              lat: -1.94,  lng:  29.87 },
  KNA: { en:'Basseterre',      fr:'Basseterre',          lat: 17.30,  lng: -62.72 },
  LCA: { en:'Castries',        fr:'Castries',            lat: 14.01,  lng: -61.00 },
  VCT: { en:'Kingstown',       fr:'Kingstown',           lat: 13.16,  lng: -61.23 },
  WSM: { en:'Apia',            fr:'Apia',                lat:-13.83,  lng:-171.76 },
  SMR: { en:'San Marino',      fr:'Saint-Marin',         lat: 43.94,  lng:  12.45 },
  STP: { en:'São Tomé',        fr:'São Tomé',            lat:  0.34,  lng:   6.73 },
  SAU: { en:'Riyadh',          fr:'Riyad',               lat: 24.69,  lng:  46.72 },
  SEN: { en:'Dakar',           fr:'Dakar',               lat: 14.72,  lng: -17.47 },
  SRB: { en:'Belgrade',        fr:'Belgrade',            lat: 44.79,  lng:  20.45 },
  SYC: { en:'Victoria',        fr:'Victoria',            lat: -4.62,  lng:  55.45 },
  SLE: { en:'Freetown',        fr:'Freetown',            lat:  8.48,  lng: -13.23 },
  SGP: { en:'Singapore',       fr:'Singapour',           lat:  1.35,  lng: 103.82 },
  SVK: { en:'Bratislava',      fr:'Bratislava',          lat: 48.15,  lng:  17.11 },
  SVN: { en:'Ljubljana',       fr:'Ljubljana',           lat: 46.06,  lng:  14.51 },
  SLB: { en:'Honiara',         fr:'Honiara',             lat: -9.43,  lng: 159.95 },
  SOM: { en:'Mogadishu',       fr:'Mogadiscio',          lat:  2.05,  lng:  45.34 },
  ZAF: { en:'Pretoria',        fr:'Pretoria',            lat:-25.75,  lng:  28.19 },
  SSD: { en:'Juba',            fr:'Djouba',              lat:  4.85,  lng:  31.58 },
  ESP: { en:'Madrid',          fr:'Madrid',              lat: 40.42,  lng:  -3.70 },
  LKA: { en:'Sri Jayawardenepura Kotte', fr:'Sri Jayawardenepura Kotte', lat: 6.89, lng: 79.90 },
  SDN: { en:'Khartoum',        fr:'Khartoum',            lat: 15.60,  lng:  32.53 },
  SUR: { en:'Paramaribo',      fr:'Paramaribo',          lat:  5.85,  lng: -55.20 },
  SWE: { en:'Stockholm',       fr:'Stockholm',           lat: 59.33,  lng:  18.07 },
  CHE: { en:'Bern',            fr:'Berne',               lat: 46.95,  lng:   7.45 },
  SYR: { en:'Damascus',        fr:'Damas',               lat: 33.51,  lng:  36.29 },
  TWN: { en:'Taipei',          fr:'Taipei',              lat: 25.03,  lng: 121.57 },
  TJK: { en:'Dushanbe',        fr:'Douchanbé',           lat: 38.56,  lng:  68.77 },
  TZA: { en:'Dodoma',          fr:'Dodoma',              lat: -6.16,  lng:  35.75 },
  THA: { en:'Bangkok',         fr:'Bangkok',             lat: 13.76,  lng: 100.50 },
  TLS: { en:'Dili',            fr:'Dili',                lat: -8.56,  lng: 125.57 },
  TGO: { en:'Lomé',            fr:'Lomé',                lat:  6.14,  lng:   1.21 },
  TON: { en:"Nuku'alofa",      fr:"Nuku'alofa",          lat:-21.21,  lng:-175.20 },
  TTO: { en:'Port of Spain',   fr:'Port-d\'Espagne',     lat: 10.66,  lng: -61.51 },
  TUN: { en:'Tunis',           fr:'Tunis',               lat: 36.81,  lng:  10.18 },
  TUR: { en:'Ankara',          fr:'Ankara',              lat: 39.93,  lng:  32.87 },
  TKM: { en:'Ashgabat',        fr:'Achgabat',            lat: 37.96,  lng:  58.38 },
  TUV: { en:'Funafuti',        fr:'Funafuti',            lat: -8.52,  lng: 179.20 },
  UGA: { en:'Kampala',         fr:'Kampala',             lat:  0.35,  lng:  32.58 },
  UKR: { en:'Kyiv',            fr:'Kiev',                lat: 50.45,  lng:  30.52 },
  ARE: { en:'Abu Dhabi',       fr:'Abou Dabi',           lat: 24.45,  lng:  54.65 },
  GBR: { en:'London',          fr:'Londres',             lat: 51.51,  lng:  -0.13 },
  USA: { en:'Washington, D.C.',fr:'Washington',          lat: 38.91,  lng: -77.04 },
  URY: { en:'Montevideo',      fr:'Montevideo',          lat:-34.88,  lng: -56.16 },
  UZB: { en:'Tashkent',        fr:'Tachkent',            lat: 41.30,  lng:  69.28 },
  VUT: { en:'Port Vila',       fr:'Port-Vila',           lat:-17.73,  lng: 168.32 },
  VEN: { en:'Caracas',         fr:'Caracas',             lat: 10.49,  lng: -66.88 },
  VNM: { en:'Hanoi',           fr:'Hanoï',               lat: 21.03,  lng: 105.85 },
  YEM: { en:"Sana'a",          fr:'Sanaa',               lat: 15.37,  lng:  44.21 },
  ZMB: { en:'Lusaka',          fr:'Lusaka',              lat:-15.39,  lng:  28.32 },
  ZWE: { en:'Harare',          fr:'Harare',              lat:-17.83,  lng:  31.05 },
  XKX: { en:'Pristina',        fr:'Pristina',            lat: 42.66,  lng:  21.17 },
  PSE: { en:'Ramallah',        fr:'Ramallah',            lat: 31.90,  lng:  35.20 },
};

/**
 * Alternate / common spellings → ISO_A3.
 * Keys must be pre-normalised (see geo.js › norm()).
 * @type {Record<string, string>}
 */
export const CAPITAL_ALIASES = {
  // Variant French / English spellings
  'pekin':              'CHN',
  'beijing':            'CHN',
  'londres':            'GBR',
  'london':             'GBR',
  'moscou':             'RUS',
  'moscow':             'RUS',
  'le caire':           'EGY',
  'cairo':              'EGY',
  'la havane':          'CUB',
  'havana':             'CUB',
  'la havana':          'CUB',
  'athenes':            'GRC',
  'athens':             'GRC',
  'copenhague':         'DNK',
  'copenhagen':         'DNK',
  'bucarest':           'ROU',
  'bucharest':          'ROU',
  'varsovie':           'POL',
  'warsaw':             'POL',
  'vienne':             'AUT',
  'vienna':             'AUT',
  'lisbonne':           'PRT',
  'lisbon':             'PRT',
  'bruxelles':          'BEL',
  'brussels':           'BEL',
  'berne':              'CHE',
  'bern':               'CHE',
  'erevan':             'ARM',
  'yerevan':            'ARM',
  'bakou':              'AZE',
  'baku':               'AZE',
  'tbilissi':           'GEO',
  'tbilisi':            'GEO',
  'teheran':            'IRN',
  'tehran':             'IRN',
  'bagdad':             'IRQ',
  'baghdad':            'IRQ',
  'jerusalem':          'ISR',
  'beyrouth':           'LBN',
  'beirut':             'LBN',
  'damas':              'SYR',
  'damascus':           'SYR',
  'riyad':              'SAU',
  'riyadh':             'SAU',
  'mascate':            'OMN',
  'muscat':             'OMN',
  'dacca':              'BGD',
  'dhaka':              'BGD',
  'katmandou':          'NPL',
  'kathmandu':          'NPL',
  'thimphou':           'BTN',
  'thimphu':            'BTN',
  'oulan bator':        'MNG',
  'ulaanbaatar':        'MNG',
  'bichkek':            'KGZ',
  'bishkek':            'KGZ',
  'douchanbe':          'TJK',
  'dushanbe':           'TJK',
  'tachkent':           'UZB',
  'tashkent':           'UZB',
  'achgabat':           'TKM',
  'ashgabat':           'TKM',
  'kaboul':             'AFG',
  'kabul':              'AFG',
  'kiev':               'UKR',
  'kyiv':               'UKR',
  'nicosie':            'CYP',
  'nicosia':            'CYP',
  'seoul':              'KOR',
  'pyongyang':          'PRK',
  'manille':            'PHL',
  'manila':             'PHL',
  'singapour':          'SGP',
  'singapore':          'SGP',
  'addis abeba':        'ETH',
  'addis ababa':        'ETH',
  'mogadiscio':         'SOM',
  'mogadishu':          'SOM',
  'djouba':             'SSD',
  'juba':               'SSD',
  'la valette':         'MLT',
  'valletta':           'MLT',
  'saint domingue':     'DOM',
  'santo domingo':      'DOM',
  'mexico':             'MEX',
  'mexico city':        'MEX',
  'guatemala':          'GTM',
  'guatemala city':     'GTM',
  'panama':             'PAN',
  'panama city':        'PAN',
  'saint marin':        'SMR',
  'san marino':         'SMR',
  'andorre la vieille': 'AND',
  'andorra la vella':   'AND',
  'port despagne':      'TTO',
  'port of spain':      'TTO',
  'abou dabi':          'ARE',
  'abu dhabi':          'ARE',
  'washington':         'USA',
  'washington dc':      'USA',
  'new delhi':          'IND',
  'sri jayawardenepura kotte': 'LKA',
  'kotte':              'LKA',
  'colombo':            'LKA',
  'la paz':             'BOL',
  'sucre':              'BOL',
  'pretoria':           'ZAF',
  'cape town':          'ZAF',
  'le cap':             'ZAF',
  'ndjamena':           'TCD',
  'ndjaména':           'TCD',
  'saint georges':      'GRD',
  'port au prince':     'HTI',
  'port louis':         'MUS',
  'port vila':          'VUT',
  'port moresby':       'PNG',
  'sanaa':              'YEM',
};
