/**
 * data.js
 * Static lookup tables:
 *   EXCLUDED_ISO2 – 2-letter codes to exclude from the game
 *   FR            – ISO_A3 → French country name
 *   ALIASES       – normalized input string → ISO_A3
 */

/**
 * Countries to exclude from the game (ISO 3166-1 Alpha-2 codes).
 * These are territories, dependencies, or minor islands that are
 * not meaningful to guess on a map.
 * Add or remove entries here to customise which countries appear.
 * @type {Set<string>}
 */
export const EXCLUDED_ISO2 = new Set([
  'UM',  // United States Minor Outlying Islands
  'AQ',  // Antarctica
  'BV',  // Bouvet Island
  'HM',  // Heard Island and McDonald Islands
  'TF',  // French Southern Territories
  'GS',  // South Georgia and the South Sandwich Islands
  'SJ',  // Svalbard and Jan Mayen
  '-99', // Not countries, but appear in the GeoJSON data
]);

/** @type {Record<string, string>} */
export const FR = {
  AFG:'Afghanistan',      ALB:'Albanie',          DZA:'Algérie',
  AND:'Andorre',          AGO:'Angola',            ATG:'Antigua-et-Barbuda',
  ARG:'Argentine',        ARM:'Arménie',           AUS:'Australie',
  AUT:'Autriche',         AZE:'Azerbaïdjan',       BHS:'Bahamas',
  BHR:'Bahreïn',          BGD:'Bangladesh',        BRB:'Barbade',
  BLR:'Biélorussie',      BEL:'Belgique',          BLZ:'Belize',
  BEN:'Bénin',            BTN:'Bhoutan',           BOL:'Bolivie',
  BIH:'Bosnie-Herzégovine', BWA:'Botswana',        BRA:'Brésil',
  BRN:'Brunéi',           BGR:'Bulgarie',          BFA:'Burkina Faso',
  BDI:'Burundi',          CPV:'Cap-Vert',          KHM:'Cambodge',
  CMR:'Cameroun',         CAN:'Canada',            CAF:'République centrafricaine',
  TCD:'Tchad',            CHL:'Chili',             CHN:'Chine',
  COL:'Colombie',         COM:'Comores',           COG:'République du Congo',
  COD:'République démocratique du Congo',          CRI:'Costa Rica',
  CIV:"Côte d'Ivoire",   HRV:'Croatie',           CUB:'Cuba',
  CYP:'Chypre',           CZE:'Tchéquie',          DNK:'Danemark',
  DJI:'Djibouti',         DMA:'Dominique',         DOM:'République dominicaine',
  ECU:'Équateur',         EGY:'Égypte',            SLV:'Salvador',
  GNQ:'Guinée équatoriale', ERI:'Érythrée',        EST:'Estonie',
  SWZ:'Eswatini',         ETH:'Éthiopie',          FJI:'Fidji',
  FIN:'Finlande',         FRA:'France',            GAB:'Gabon',
  GMB:'Gambie',           GEO:'Géorgie',           DEU:'Allemagne',
  GHA:'Ghana',            GRC:'Grèce',             GRD:'Grenade',
  GTM:'Guatemala',        GIN:'Guinée',            GNB:'Guinée-Bissau',
  GUY:'Guyana',           HTI:'Haïti',             HND:'Honduras',
  HUN:'Hongrie',          ISL:'Islande',           IND:'Inde',
  IDN:'Indonésie',        IRN:'Iran',              IRQ:'Irak',
  IRL:'Irlande',          ISR:'Israël',            ITA:'Italie',
  JAM:'Jamaïque',         JPN:'Japon',             JOR:'Jordanie',
  KAZ:'Kazakhstan',       KEN:'Kenya',             KIR:'Kiribati',
  PRK:'Corée du Nord',    KOR:'Corée du Sud',      KWT:'Koweït',
  KGZ:'Kirghizistan',     LAO:'Laos',              LVA:'Lettonie',
  LBN:'Liban',            LSO:'Lesotho',           LBR:'Libéria',
  LBY:'Libye',            LIE:'Liechtenstein',     LTU:'Lituanie',
  LUX:'Luxembourg',       MDG:'Madagascar',        MWI:'Malawi',
  MYS:'Malaisie',         MDV:'Maldives',          MLI:'Mali',
  MLT:'Malte',            MHL:'Îles Marshall',     MRT:'Mauritanie',
  MUS:'Maurice',          MEX:'Mexique',           FSM:'Micronésie',
  MDA:'Moldavie',         MCO:'Monaco',            MNG:'Mongolie',
  MNE:'Monténégro',       MAR:'Maroc',             MOZ:'Mozambique',
  MMR:'Birmanie',         NAM:'Namibie',           NRU:'Nauru',
  NPL:'Népal',            NLD:'Pays-Bas',          NZL:'Nouvelle-Zélande',
  NIC:'Nicaragua',        NER:'Niger',             NGA:'Nigéria',
  MKD:'Macédoine du Nord', NOR:'Norvège',          OMN:'Oman',
  PAK:'Pakistan',         PLW:'Palaos',            PAN:'Panama',
  PNG:'Papouasie-Nouvelle-Guinée', PRY:'Paraguay', PER:'Pérou',
  PHL:'Philippines',      POL:'Pologne',           PRT:'Portugal',
  QAT:'Qatar',            ROU:'Roumanie',          RUS:'Russie',
  RWA:'Rwanda',           KNA:'Saint-Christophe-et-Niévès',
  LCA:'Sainte-Lucie',     VCT:'Saint-Vincent-et-les-Grenadines',
  WSM:'Samoa',            SMR:'Saint-Marin',       STP:'Sao Tomé-et-Principe',
  SAU:'Arabie saoudite',  SEN:'Sénégal',           SRB:'Serbie',
  SYC:'Seychelles',       SLE:'Sierra Leone',      SGP:'Singapour',
  SVK:'Slovaquie',        SVN:'Slovénie',          SLB:'Îles Salomon',
  SOM:'Somalie',          ZAF:'Afrique du Sud',    SSD:'Soudan du Sud',
  ESP:'Espagne',          LKA:'Sri Lanka',         SDN:'Soudan',
  SUR:'Suriname',         SWE:'Suède',             CHE:'Suisse',
  SYR:'Syrie',            TWN:'Taïwan',            TJK:'Tadjikistan',
  TZA:'Tanzanie',         THA:'Thaïlande',         TLS:'Timor oriental',
  TGO:'Togo',             TON:'Tonga',             TTO:'Trinité-et-Tobago',
  TUN:'Tunisie',          TUR:'Turquie',           TKM:'Turkménistan',
  TUV:'Tuvalu',           UGA:'Ouganda',           UKR:'Ukraine',
  ARE:'Émirats arabes unis', GBR:'Royaume-Uni',    USA:'États-Unis',
  URY:'Uruguay',          UZB:'Ouzbékistan',       VUT:'Vanuatu',
  VEN:'Venezuela',        VNM:'Viêt Nam',          YEM:'Yémen',
  ZMB:'Zambie',           ZWE:'Zimbabwe',          XKX:'Kosovo',
  PSE:'Palestine',        SXM:'Saint-Martin',      CUW:'Curaçao',
};

/**
 * Keys must already be normalised (see geo.js › norm()).
 * Values are ISO_A3 codes.
 * @type {Record<string, string>}
 */
export const ALIASES = {
  // Americas
  'usa':                  'USA',  'us':                 'USA',
  'america':              'USA',  'etats unis':         'USA',
  'etat unis':            'USA',
  'mexique':              'MEX',  'bresil':             'BRA',
  'brazil':               'BRA',  'colombie':           'COL',
  'bolivie':              'BOL',  'perou':              'PER',
  'peru':                 'PER',  'chili':              'CHL',
  'equateur':             'ECU',  'ecuador':            'ECU',
  'guyana':               'GUY',  'suriname':           'SUR',
  'paraguay':             'PRY',  'uruguay':            'URY',
  'venezuela':            'VEN',
  'guatemala':            'GTM',  'honduras':           'HND',
  'nicaragua':            'NIC',  'costa rica':         'CRI',
  'panama':               'PAN',  'belize':             'BLZ',
  'salvador':             'SLV',  'el salvador':        'SLV',
  'cuba':                 'CUB',
  'haïti':                'HTI',  'haiti':              'HTI',
  'jamaïque':             'JAM',  'jamaique':           'JAM',  'jamaica':  'JAM',
  'trinite':              'TTO',  'trinidad':           'TTO',
  'grenade':              'GRD',  'grenada':            'GRD',
  'barbade':              'BRB',  'barbados':           'BRB',
  'antigua':              'ATG',  'antigua et barbuda': 'ATG',
  'saint kitts':          'KNA',  'saint-kitts':        'KNA',
  'sainte lucie':         'LCA',  'saint lucia':        'LCA',
  'saint vincent':        'VCT',
  'dominique':            'DMA',

  // Europe
  'uk':                   'GBR',  'angleterre':         'GBR',
  'grande bretagne':      'GBR',  'bretagne':           'GBR',
  'ecosse':               'GBR',  'pays de galles':     'GBR',
  'allemagne':            'DEU',  'germany':            'DEU',
  'hollande':             'NLD',  'netherlands':        'NLD',
  'pays bas':             'NLD',
  'espagne':              'ESP',  'spain':              'ESP',
  'italie':               'ITA',  'italy':              'ITA',
  'portugal':             'PRT',
  'belgique':             'BEL',  'belgium':            'BEL',
  'suisse':               'CHE',  'switzerland':        'CHE',
  'autriche':             'AUT',  'austria':            'AUT',
  'pologne':              'POL',  'poland':             'POL',
  'hongrie':              'HUN',  'hungary':            'HUN',
  'roumanie':             'ROU',  'romania':            'ROU',
  'bulgarie':             'BGR',  'bulgaria':           'BGR',
  'grece':                'GRC',  'greece':             'GRC',
  'serbie':               'SRB',  'serbia':             'SRB',
  'croatie':              'HRV',
  'slovenie':             'SVN',  'slovaquie':          'SVK',
  'bosnie':               'BIH',  'bosnia':             'BIH',
  'macedoine':            'MKD',  'north macedonia':    'MKD',
  'monténégro':           'MNE',  'montenegro':         'MNE',
  'moldavie':             'MDA',  'moldova':            'MDA',
  'bielorussie':          'BLR',  'belarus':            'BLR',
  'ukraine':              'UKR',
  'lituanie':             'LTU',  'lithuania':          'LTU',
  'lettonie':             'LVA',  'latvia':             'LVA',
  'estonie':              'EST',  'estonia':            'EST',
  'finlande':             'FIN',  'finland':            'FIN',
  'suede':                'SWE',  'sweden':             'SWE',
  'norvege':              'NOR',  'norway':             'NOR',
  'danemark':             'DNK',  'denmark':            'DNK',
  'islande':              'ISL',  'iceland':            'ISL',
  'irlande':              'IRL',  'ireland':            'IRL',
  'luxembourg':           'LUX',  'andorre':            'AND',
  'andorra':              'AND',  'monaco':             'MCO',
  'liechtenstein':        'LIE',  'malte':              'MLT',
  'chypre':               'CYP',  'cyprus':             'CYP',
  'saint marin':          'SMR',  'san marino':         'SMR',
  'kosovo':               'XKX',

  // Africa
  'maroc':                'MAR',  'morocco':            'MAR',
  'algerie':              'DZA',  'algeria':            'DZA',
  'tunisie':              'TUN',  'tunisia':            'TUN',
  'egypte':               'EGY',  'egypt':              'EGY',
  'libye':                'LBY',  'libya':              'LBY',
  'mauritanie':           'MRT',  'mauritania':         'MRT',
  'mali':                 'MLI',  'niger':              'NER',
  'tchad':                'TCD',  'chad':               'TCD',
  'soudan':               'SDN',  'sudan':              'SDN',
  'soudan du sud':        'SSD',  'south sudan':        'SSD',
  'ethiopie':             'ETH',  'ethiopia':           'ETH',
  'erythree':             'ERI',  'eritrea':            'ERI',
  'djibouti':             'DJI',  'somalie':            'SOM',
  'somalia':              'SOM',
  'kenya':                'KEN',  'ouganda':            'UGA',
  'uganda':               'UGA',  'rwanda':             'RWA',
  'burundi':              'BDI',  'tanzanie':           'TZA',
  'ghana':                'GHA',  'togo':               'TGO',
  'benin':                'BEN',
  'senegal':              'SEN',  'gambie':             'GMB',
  'guinee':               'GIN',  'guinea':             'GIN',
  'guinee bissau':        'GNB',  'guinea-bissau':      'GNB',
  'sierra leone':         'SLE',  'liberia':            'LBR',
  'libéria':              'LBR',
  'burkina':              'BFA',  'burkina faso':       'BFA',
  'nigeria':              'NGA',  'nigéria':            'NGA',
  'cameroun':             'CMR',  'cameroon':           'CMR',
  'guinee equatoriale':   'GNQ',  'equatorial guinea':  'GNQ',
  'gabon':                'GAB',
  'congo':                'COG',  'congo brazza':       'COG',
  'rdc':                  'COD',  'drc':                'COD',
  'dr congo':             'COD',
  'angola':               'AGO',  'zambie':             'ZMB',
  'zambia':               'ZMB',  'mozambique':         'MOZ',
  'zimbabwe':             'ZWE',  'namibie':            'NAM',
  'namibia':              'NAM',  'botswana':           'BWA',
  'afrique du sud':       'ZAF',  'south africa':       'ZAF',
  'lesotho':              'LSO',  'eswatini':           'SWZ',
  'swaziland':            'SWZ',  'madagascar':         'MDG',
  'comores':              'COM',  'comoros':            'COM',
  'seychelles':           'SYC',  'maurice':            'MUS',
  'mauritius':            'MUS',
  'cap vert':             'CPV',  'cabo verde':         'CPV',
  'sao tome':             'STP',  'sao tome et principe':'STP',

  // Middle East
  'arabie':               'SAU',  'saudi':              'SAU',
  'saudi arabia':         'SAU',  'arabie saoudite':    'SAU',
  'emirats arabes':       'ARE',  'uae':                'ARE',
  'koweït':               'KWT',  'koweit':             'KWT',
  'kuwait':               'KWT',  'oman':               'OMN',
  'qatar':                'QAT',  'yémen':              'YEM',
  'yemen':                'YEM',  'bahrain':            'BHR',
  'bahreïn':              'BHR',
  'jordanie':             'JOR',  'jordan':             'JOR',
  'liban':                'LBN',  'lebanon':            'LBN',
  'syrie':                'SYR',  'syria':              'SYR',
  'israel':               'ISR',  'palestine':          'PSE',
  'irak':                 'IRQ',  'iraq':               'IRQ',
  'iran':                 'IRN',

  // Asia
  'russie':               'RUS',  'russland':           'RUS',
  'chine':                'CHN',  'china':              'CHN',
  'japon':                'JPN',  'japan':              'JPN',
  'coree du nord':        'PRK',  'north korea':        'PRK',
  'coree du sud':         'KOR',  'south korea':        'KOR',
  'coree':                'KOR',
  'mongolie':             'MNG',  'mongolia':           'MNG',
  'kazakhstan':           'KAZ',
  'kirghizistan':         'KGZ',  'kyrgyzstan':         'KGZ',
  'kirghizie':            'KGZ',
  'tadjikistan':          'TJK',  'tajikistan':         'TJK',
  'ouzbekistan':          'UZB',  'uzbekistan':         'UZB',
  'turkmenistan':         'TKM',
  'azerbaidjan':          'AZE',  'azerbaijan':         'AZE',
  'armenie':              'ARM',  'armenia':            'ARM',
  'georgie':              'GEO',  'georgia':            'GEO',
  'inde':                 'IND',  'india':              'IND',
  'pakistan':             'PAK',  'nepal':              'NPL',
  'népal':                'NPL',  'bhoutan':            'BTN',
  'bhutan':               'BTN',  'bangladesh':         'BGD',
  'sri lanka':            'LKA',  'maldives':           'MDV',
  'birmanie':             'MMR',  'myanmar':            'MMR',
  'cambodge':             'KHM',  'cambodia':           'KHM',
  'laos':                 'LAO',  'vietnam':            'VNM',
  'viet nam':             'VNM',
  'thaïlande':            'THA',  'thailande':          'THA',
  'thailand':             'THA',
  'malaisie':             'MYS',  'malaysia':           'MYS',
  'indonesie':            'IDN',  'indonesia':          'IDN',
  'philippines':          'PHL',
  'singapour':            'SGP',  'singapore':          'SGP',
  'brunei':               'BRN',  'timor':              'TLS',
  'east timor':           'TLS',  'turquie':            'TUR',
  'turkey':               'TUR',

  // Oceania
  'australie':            'AUS',  'australia':          'AUS',
  'nouvelle zelande':     'NZL',  'new zealand':        'NZL',
  'papouasie':            'PNG',  'papua':              'PNG',
  'fidji':                'FJI',  'fiji':               'FJI',
  'iles salomon':         'SLB',  'solomon islands':    'SLB',
  'vanuatu':              'VUT',  'nauru':              'NRU',
  'tuvalu':               'TUV',  'tonga':              'TON',
  'samoa':                'WSM',  'kiribati':           'KIR',
  'iles marshall':        'MHL',  'marshall islands':   'MHL',
  'micronesie':           'FSM',  'micronesia':         'FSM',
  'palaos':               'PLW',  'palau':              'PLW',

  // Czech shortcuts
  'tcheque':              'CZE',  'republique tcheque': 'CZE',
  'czech republic':       'CZE',  'czech':              'CZE',
  'czechia':              'CZE',
};
